"""Per-course content for /golf/course/<slug> landing pages.

Anchored to facts: course name, city (from PGA_COURSES). Weather angles
are based on well-known geographic and climate characteristics of each
venue's region and typical PGA Tour visit window.
"""

COURSE_CONTENT = {
    "Augusta National Golf Club": {"slug": "augusta-national",
        "headline": "Augusta National Weather: Masters Week Georgia Spring",
        "intro": "Augusta National hosts the Masters every April in Augusta, Georgia. Southeast spring weather brings warm humid conditions with elevated afternoon thunderstorm risk. Pollen counts are significant. The course sits in a bowl that can channel wind through Amen Corner in unpredictable ways.",
        "angle": "Thunderstorm delays and wind-affected par-5 second shots at 13 and 15 are the primary weather angles at the Masters. Cool spring mornings produce different ball flight than warm afternoon rounds."},
    "Pinehurst Resort & Country Club": {"slug": "pinehurst-no2",
        "headline": "Pinehurst No. 2 Weather: Sandhills North Carolina Summer",
        "intro": "Pinehurst No. 2 in the North Carolina Sandhills hosts US Opens in June. Southeast summer heat and humidity are the primary conditions with afternoon thunderstorm risk from the Piedmont.",
        "angle": "Heat and humidity affect ball flight and player stamina on the treeless Sandhills layout. Afternoon storm delays are common."},
    "Oakmont Country Club": {"slug": "oakmont",
        "headline": "Oakmont Weather: Pittsburgh Championship Golf",
        "intro": "Oakmont Country Club near Pittsburgh hosts US Opens in June. Ohio Valley climate brings warm humid conditions with cold-front-driven thunderstorm risk.",
        "angle": "Heat and afternoon storm risk are the primary weather angles. Oakmont's fast greens react to moisture; rain softens the course significantly."},
    "Bethpage Black Course": {"slug": "bethpage-black",
        "headline": "Bethpage Black Weather: Long Island Championship Golf",
        "intro": "Bethpage Black on Long Island hosts US Opens and PGA Championships. Coastal Northeast climate brings variable spring and summer conditions with sea breeze influence.",
        "angle": "Coastal wind and moisture are the primary weather angles. Sea breeze shifts through the day can change club selection between morning and afternoon rounds."},
    "Quail Hollow Club": {"slug": "quail-hollow",
        "headline": "Quail Hollow Weather: Charlotte North Carolina PGA Championship Venue",
        "intro": "Quail Hollow in Charlotte hosts the PGA Championship and Wells Fargo Championship. Southeast climate brings warm humid spring and summer conditions with Piedmont thunderstorm risk.",
        "angle": "Southeast humidity affects ball flight; afternoon storm delays are common in May and August tournament windows."},
    "Royal Liverpool Golf Club": {"slug": "royal-liverpool",
        "headline": "Royal Liverpool (Hoylake) Weather: Open Championship Links Golf",
        "intro": "Royal Liverpool in Hoylake, England hosts the Open Championship. Coastal links course with typical British Isles maritime weather: variable wind, rain risk, and cool temperatures even in July.",
        "angle": "Wind and rain are the defining Open Championship weather. Links golf is designed for these conditions; players who handle wet and windy links play best."},
    "Royal Troon Golf Club": {"slug": "royal-troon",
        "headline": "Royal Troon Weather: Scottish Open Championship Links",
        "intro": "Royal Troon on the Scottish west coast hosts the Open Championship. Maritime climate produces variable wind, frequent rain, and cool temperatures.",
        "angle": "Scottish links weather is the defining feature. Cool damp conditions and sustained wind reward links specialists."},
    "Shinnecock Hills Golf Club": {"slug": "shinnecock-hills",
        "headline": "Shinnecock Hills Weather: Long Island US Open Links",
        "intro": "Shinnecock Hills on eastern Long Island hosts US Opens. Coastal setting with true links characteristics. Late-spring and summer play is affected by Atlantic sea breeze and coastal wind.",
        "angle": "Coastal wind is the defining feature. Fast fescue fairways react dramatically to wind and moisture changes."},
    "Royal Birkdale Golf Club": {"slug": "royal-birkdale",
        "headline": "Royal Birkdale Weather: Southport England Links",
        "intro": "Royal Birkdale in Southport, England hosts the Open Championship. Northwest England maritime climate produces variable wind and frequent rain.",
        "angle": "Links weather with sustained wind and rain risk. Cool damp conditions favor players comfortable with British Isles play."},
    "TPC Sawgrass": {"slug": "tpc-sawgrass",
        "headline": "TPC Sawgrass Weather: Players Championship Florida",
        "intro": "TPC Sawgrass in Ponte Vedra Beach hosts the Players Championship in March. Northeast Florida spring weather brings variable conditions; cold fronts can bring wind and cool temperatures.",
        "angle": "Wind at the island-green 17th is the iconic Sawgrass weather angle. Coastal wind shifts change club selection dramatically."},
    "Pebble Beach Golf Links": {"slug": "pebble-beach",
        "headline": "Pebble Beach Weather: California Coastal Championship Golf",
        "intro": "Pebble Beach on the Monterey Peninsula hosts the AT&T Pebble Beach Pro-Am in February and US Opens. Pacific coastal setting brings marine layer, wind, and cool temperatures.",
        "angle": "Marine layer fog and sustained Pacific wind are the defining features. Cool damp conditions affect ball flight significantly on the ocean holes."},
    "Riviera Country Club": {"slug": "riviera-country-club",
        "headline": "Riviera Country Club Weather: Los Angeles Genesis Invitational",
        "intro": "Riviera in Pacific Palisades hosts the Genesis Invitational in February. Southern California coastal climate brings mild conditions with occasional winter rain.",
        "angle": "February Los Angeles rain risk is the primary weather variable. Santa Ana wind events in fall are less relevant for the tournament window."},
    "Torrey Pines Golf Course": {"slug": "torrey-pines",
        "headline": "Torrey Pines Weather: San Diego Coastal Golf",
        "intro": "Torrey Pines in La Jolla hosts the Farmers Insurance Open in January and US Opens. Pacific bluff setting with marine layer and coastal wind.",
        "angle": "Marine layer and coastal wind are the primary weather features. January winter rain risk is elevated relative to the summer tour baseline."},
    "TPC Scottsdale": {"slug": "tpc-scottsdale",
        "headline": "TPC Scottsdale Weather: Waste Management Phoenix Open",
        "intro": "TPC Scottsdale hosts the Waste Management Phoenix Open in February. Sonoran Desert climate brings dry mild winter conditions.",
        "angle": "Consistent dry cool conditions predominate. Wind is generally light; rain is uncommon."},
    "Bay Hill Club and Lodge": {"slug": "bay-hill",
        "headline": "Bay Hill Weather: Arnold Palmer Invitational Orlando",
        "intro": "Bay Hill in Orlando hosts the Arnold Palmer Invitational in March. Central Florida spring brings warm humid conditions with occasional cold-front-driven wind and rain.",
        "angle": "Wind and cold-front-driven weather shifts are the primary variables in the March tournament window."},
    "PGA National Resort": {"slug": "pga-national",
        "headline": "PGA National Weather: Honda Classic Palm Beach",
        "intro": "PGA National in Palm Beach Gardens hosts the Honda Classic in February and March. South Florida coastal climate brings warm humid conditions with sustained coastal wind.",
        "angle": "The Bear Trap's exposure to sustained coastal wind is the defining PGA National weather feature. Cold fronts through Florida can drop temperatures and increase wind."},
    "Innisbrook Resort (Copperhead Course)": {"slug": "innisbrook-copperhead",
        "headline": "Innisbrook Copperhead Weather: Valspar Championship Florida",
        "intro": "Innisbrook Copperhead in Palm Harbor, Florida hosts the Valspar Championship in March. Gulf Coast Florida climate brings warm humid spring conditions.",
        "angle": "Cold-front-driven wind and afternoon thunderstorm risk are the primary weather variables."},
    "Memorial Park Golf Course": {"slug": "memorial-park",
        "headline": "Memorial Park Weather: Houston Open Municipal Course",
        "intro": "Memorial Park in Houston hosts the Texas Children's Houston Open. Gulf Coast climate with warm humid conditions and afternoon thunderstorm risk.",
        "angle": "Houston heat and thunderstorm risk are the primary weather angles. Gulf-driven wind affects the exposed layout."},
    "Colonial Country Club": {"slug": "colonial-country-club",
        "headline": "Colonial Country Club Weather: Charles Schwab Challenge Fort Worth",
        "intro": "Colonial in Fort Worth hosts the Charles Schwab Challenge in May. North Texas spring brings warm conditions with severe-weather risk from Great Plains storm systems.",
        "angle": "Severe-weather delays and sustained plains wind are the primary weather variables. Radar risk is elevated in May."},
    "Muirfield Village Golf Club": {"slug": "muirfield-village",
        "headline": "Muirfield Village Weather: Memorial Tournament Ohio",
        "intro": "Muirfield Village in Dublin, Ohio hosts the Memorial Tournament in early June. Ohio Valley late-spring climate brings warm humid conditions with elevated thunderstorm risk.",
        "angle": "Afternoon thunderstorm delays and cold-front wind shifts are the primary weather angles in June."},
    "TPC River Highlands": {"slug": "tpc-river-highlands",
        "headline": "TPC River Highlands Weather: Travelers Championship Connecticut",
        "intro": "TPC River Highlands in Cromwell, Connecticut hosts the Travelers Championship in June. Southern New England climate brings warm humid summer conditions with thunderstorm risk.",
        "angle": "Afternoon thunderstorm delays and wind are the primary weather variables. Coastal Connecticut can see sea-breeze influence."},
    "TPC Twin Cities": {"slug": "tpc-twin-cities",
        "headline": "TPC Twin Cities Weather: 3M Open Minnesota",
        "intro": "TPC Twin Cities in Blaine, Minnesota hosts the 3M Open in July. Upper Midwest climate brings warm humid summer conditions with plains wind and thunderstorm risk.",
        "angle": "Plains wind and severe-weather risk are the primary July weather variables in Minnesota."},
    "Detroit Golf Club": {"slug": "detroit-golf-club",
        "headline": "Detroit Golf Club Weather: Rocket Mortgage Classic Detroit",
        "intro": "Detroit Golf Club hosts the Rocket Mortgage Classic in late June or July. Great Lakes climate brings warm humid summer conditions with lake influence and thunderstorm risk.",
        "angle": "Lake-driven weather patterns and afternoon thunderstorm delays are the primary weather angles."},
    "Detroit Country Club (Country Club of Detroit)": {"slug": "country-club-of-detroit",
        "headline": "Country Club of Detroit Weather: Grosse Pointe Farms Golf",
        "intro": "The Country Club of Detroit in Grosse Pointe Farms sits on the shore of Lake St. Clair. Great Lakes climate with lake influence.",
        "angle": "Lake-influenced wind and cool marine air are the primary weather features."},
    "TPC Deere Run": {"slug": "tpc-deere-run",
        "headline": "TPC Deere Run Weather: John Deere Classic Illinois",
        "intro": "TPC Deere Run in Silvis, Illinois hosts the John Deere Classic in July. Upper Midwest summer climate brings warm humid conditions with thunderstorm risk.",
        "angle": "Afternoon thunderstorm delays and Great Plains wind are the primary weather variables."},
    "Renaissance Club": {"slug": "renaissance-club",
        "headline": "Renaissance Club Weather: Scottish Open Links",
        "intro": "Renaissance Club in North Berwick, Scotland hosts the Scottish Open in July. Coastal links weather with variable wind and rain.",
        "angle": "Scottish coastal links weather is the defining feature; cool wet windy conditions favor links specialists."},
    "TPC Southwind": {"slug": "tpc-southwind",
        "headline": "TPC Southwind Weather: FedEx St. Jude Championship Memphis",
        "intro": "TPC Southwind in Memphis hosts the FedEx St. Jude Championship in August. Mid-South summer climate brings hot humid conditions with high heat index.",
        "angle": "Extreme August heat and afternoon thunderstorm risk are the primary weather variables. Player heat management is a factor."},
    "Olympia Fields Country Club": {"slug": "olympia-fields",
        "headline": "Olympia Fields Weather: BMW Championship Chicago",
        "intro": "Olympia Fields near Chicago hosts the BMW Championship. Late-summer Midwest climate brings variable weather with cold-front risk.",
        "angle": "Cold-front-driven wind shifts and afternoon thunderstorm risk are the primary late-summer weather variables."},
    "East Lake Golf Club": {"slug": "east-lake",
        "headline": "East Lake Weather: Tour Championship Atlanta",
        "intro": "East Lake in Atlanta hosts the season-ending Tour Championship in late August. Southeast late-summer climate brings hot humid conditions with thunderstorm risk.",
        "angle": "Extreme heat and afternoon thunderstorm delays are the primary weather variables for the championship."},
    "Castle Pines Golf Club": {"slug": "castle-pines",
        "headline": "Castle Pines Weather: BMW Championship Colorado Elevation",
        "intro": "Castle Pines in Castle Rock, Colorado sits at over 6,000 feet of elevation. Rocky Mountain climate produces variable summer weather with severe-weather risk.",
        "angle": "Elevation is the defining Castle Pines factor; thin air adds significant distance. Afternoon thunderstorm risk is elevated in the summer tournament window."},
    "Sedgefield Country Club": {"slug": "sedgefield",
        "headline": "Sedgefield Weather: Wyndham Championship North Carolina",
        "intro": "Sedgefield in Greensboro, North Carolina hosts the Wyndham Championship in August. Southeast summer climate brings hot humid conditions with thunderstorm risk.",
        "angle": "August heat and afternoon storm risk are the primary weather variables."},
    "Bellerive Country Club": {"slug": "bellerive",
        "headline": "Bellerive Country Club Weather: St. Louis Championship Golf",
        "intro": "Bellerive in Town and Country, Missouri near St. Louis hosts PGA Championships. Midwest summer climate brings warm humid conditions with thunderstorm risk.",
        "angle": "Heat and cold-front-driven storm risk are the primary weather variables."},
    "The Cliffs at Walnut Cove": {"slug": "walnut-cove",
        "headline": "The Cliffs at Walnut Cove Weather: Asheville Mountain Golf",
        "intro": "The Cliffs at Walnut Cove near Asheville, North Carolina sits in the Blue Ridge Mountains. Mountain climate with variable weather and cooler temperatures than the Piedmont.",
        "angle": "Mountain weather variability including afternoon thunderstorm risk and cool morning temperatures affect play."},
    "Medinah CC (No. 3)": {"slug": "medinah-no3",
        "headline": "Medinah No. 3 Weather: Chicago Area Championship Golf",
        "intro": "Medinah Country Club No. 3 near Chicago hosts PGA Championships and Ryder Cup events. Midwest climate with lake-driven weather influence.",
        "angle": "Lake-influenced wind and afternoon thunderstorm risk are the primary weather variables."},
    "Sea Island Resort (Seaside Course)": {"slug": "sea-island-seaside",
        "headline": "Sea Island Seaside Weather: RSM Classic Coastal Georgia",
        "intro": "Sea Island Seaside on St. Simons Island hosts the RSM Classic in November. Coastal Georgia autumn brings mild conditions with coastal wind and occasional cold fronts.",
        "angle": "Coastal wind and November cold-front risk are the primary weather variables."},
    "Country Club of Jackson": {"slug": "country-club-of-jackson",
        "headline": "Country Club of Jackson Weather: Sanderson Farms Championship Mississippi",
        "intro": "Country Club of Jackson in Mississippi hosts the Sanderson Farms Championship in October. Mid-South autumn climate brings mild conditions with occasional cold-front risk.",
        "angle": "Cold-front-driven wind and cool temperatures are the primary October weather variables."},
    "El Camaleón Golf Club": {"slug": "el-camaleon",
        "headline": "El Camaleón Weather: World Wide Technology Championship Playa del Carmen",
        "intro": "El Camaleón in Playa del Carmen, Mexico hosts the World Wide Technology Championship in November. Yucatan Peninsula climate brings warm humid conditions with tropical wind.",
        "angle": "Coastal wind and rare late-season tropical-system risk are the primary weather variables."},
    "Plantation Course at Kapalua": {"slug": "kapalua-plantation",
        "headline": "Kapalua Plantation Weather: Sentry Tournament of Champions Maui",
        "intro": "Kapalua Plantation Course on Maui hosts the Sentry Tournament of Champions in January. Hawaiian tradewind climate brings warm conditions with sustained tradewinds.",
        "angle": "Tradewinds are the defining Kapalua weather. Sustained wind of 15 to 25 mph is normal and affects every club selection."},
    "Waialae Country Club": {"slug": "waialae",
        "headline": "Waialae Weather: Sony Open Honolulu Coastal Golf",
        "intro": "Waialae Country Club in Honolulu hosts the Sony Open in January. Hawaiian coastal climate brings warm conditions with tradewinds and occasional rain.",
        "angle": "Tradewinds and coastal moisture are the primary weather features. Wind can be strong through the tournament week."},
    "Black Desert Resort": {"slug": "black-desert-resort",
        "headline": "Black Desert Resort Weather: Southern Utah Desert Golf",
        "intro": "Black Desert Resort in Ivins, Utah hosts the Black Desert Championship. Southern Utah desert climate brings dry mild autumn conditions with elevation effects.",
        "angle": "Dry desert air and moderate elevation affect ball flight. Wind is generally light."},
    "Omni Barton Creek Resort": {"slug": "barton-creek",
        "headline": "Barton Creek Weather: ATX Championship Austin Texas Hill Country",
        "intro": "Omni Barton Creek in Austin sits in the Texas Hill Country. Central Texas climate with warm conditions and variable spring weather.",
        "angle": "Spring severe-weather risk and summer heat are the primary weather variables depending on tournament timing."},
    "Tiburon Golf Club": {"slug": "tiburon-golf-club",
        "headline": "Tiburon Weather: Naples Florida Autumn Golf",
        "intro": "Tiburon in Naples, Florida hosts autumn PGA Tour events. Gulf Coast Florida climate brings warm humid conditions with rare late-season tropical-storm risk.",
        "angle": "Warm humid conditions with occasional cold-front influence are the primary autumn weather variables."},
    "Yokohama Country Club": {"slug": "yokohama-country-club",
        "headline": "Yokohama Country Club Weather: Japan Championship Golf",
        "intro": "Yokohama Country Club in Japan hosts PGA Tour events. Kanto region climate brings variable autumn weather with typhoon-season risk into October.",
        "angle": "Typhoon-season risk in October and coastal Pacific wind are the primary weather variables."},
    "Port Royal Golf Course": {"slug": "port-royal",
        "headline": "Port Royal Weather: Bermuda Championship Coastal Golf",
        "intro": "Port Royal in Bermuda hosts the Butterfield Bermuda Championship. Bermuda's mid-Atlantic coastal climate brings warm conditions with sustained coastal wind.",
        "angle": "Coastal wind is the defining feature. Late-season Atlantic-storm influence is a real factor in the November tournament window."},
    "Vidanta Vallarta": {"slug": "vidanta-vallarta",
        "headline": "Vidanta Vallarta Weather: Mexico Open Puerto Vallarta",
        "intro": "Vidanta Vallarta on Mexico's Pacific coast hosts the Mexico Open. Pacific coastal climate brings warm humid conditions with tropical influence.",
        "angle": "Coastal Pacific wind and tropical rain risk are the primary weather variables."},
    "El Cardonal at Diamante": {"slug": "el-cardonal",
        "headline": "El Cardonal Weather: Los Cabos Pacific Coast Golf",
        "intro": "El Cardonal at Diamante in Los Cabos hosts PGA Tour events. Baja California Sur climate brings dry warm conditions with occasional Pacific storm influence.",
        "angle": "Dry warm conditions predominate. Pacific wind and rare storm influence are the main weather variance."},
    "Albany GC": {"slug": "albany-gc",
        "headline": "Albany GC Weather: Bahamas Coastal Golf",
        "intro": "Albany Golf Club in Nassau hosts the Hero World Challenge in December. Bahamas coastal climate brings warm winter conditions with coastal wind.",
        "angle": "Coastal wind and December warmth are the defining features. Late-year tropical-system risk is minimal."},
    "TPC Toronto at Osprey Valley": {"slug": "tpc-toronto-osprey-valley",
        "headline": "TPC Toronto at Osprey Valley Weather: Canadian Open Ontario",
        "intro": "TPC Toronto at Osprey Valley near Toronto hosts the RBC Canadian Open. Great Lakes climate brings warm humid summer conditions with variable weather.",
        "angle": "Great Lakes summer weather including afternoon thunderstorm risk is the primary variable."},
}

COURSE_BY_SLUG = {c["slug"]: (name, c) for name, c in COURSE_CONTENT.items()}
