"""Per-MLS-entity content for /mls/team/<slug> and /mls/stadium/<slug>
landing pages.

Anchored to facts from mls.venues.MLS_TEAMS: stadium name, city, roof
type, capacity, conference. Content follows the same voice as MLB/NFL:
verifiable facts only, no unsourced climatology numbers, DFS/bettor
audience where applicable.
"""

CONFS = {
    "East": ["Atlanta United FC", "Charlotte FC", "Chicago Fire FC", "FC Cincinnati",
             "Columbus Crew", "D.C. United", "Inter Miami CF", "CF Montreal",
             "Nashville SC", "New England Revolution", "New York City FC",
             "New York Red Bulls", "Orlando City SC", "Philadelphia Union", "Toronto FC"],
    "West": ["Austin FC", "Colorado Rapids", "FC Dallas", "Houston Dynamo FC",
             "LA Galaxy", "Los Angeles FC", "Minnesota United FC", "Portland Timbers",
             "Real Salt Lake", "San Diego FC", "San Jose Earthquakes",
             "Seattle Sounders FC", "Sporting Kansas City", "St. Louis City SC",
             "Vancouver Whitecaps FC"],
}
TEAM_TO_CONF_MLS = {t: c for c, ts in CONFS.items() for t in ts}


TEAM_CONTENT_MLS = {
    "Atlanta United FC": {"slug": "atlanta-united", "stadium": "Mercedes-Benz Stadium",
        "headline": "Atlanta United Weather Playbook: Mercedes-Benz Stadium Retractable Roof",
        "home": "Atlanta plays in Mercedes-Benz Stadium in downtown Atlanta. Retractable roof; MLS matches often play with the roof closed for heat, rain, or cold. Closed-roof conditions are climate-controlled with no weather variance.",
        "road": "Eastern Conference road environments span Miami warm humid, DC mid-Atlantic, Toronto retractable, New England coastal, Chicago Soldier Field open-air.",
        "angle": "Roof status is the day-of-match leverage. Closed roof removes weather; open roof plays as warm humid Southeast conditions."},
    "Charlotte FC": {"slug": "charlotte-fc", "stadium": "Bank of America Stadium",
        "headline": "Charlotte FC Weather Playbook: Bank of America Stadium and Piedmont Conditions",
        "home": "Charlotte FC plays at Bank of America Stadium in downtown Charlotte, shared with the NFL Panthers. Open-air stadium, Southeast climate with warm humid summer conditions.",
        "road": "Eastern Conference road trips into Miami warm humid, Atlanta retractable, DC mid-Atlantic, Toronto retractable.",
        "angle": "Late-season cold-front games are the main weather angle. Summer heat and afternoon thunderstorm risk are the primary variables."},
    "Chicago Fire FC": {"slug": "chicago-fire", "stadium": "Soldier Field",
        "headline": "Chicago Fire FC Weather Playbook: Soldier Field Lakefront",
        "home": "Chicago Fire plays at Soldier Field on the Chicago lakefront. Direct lakefront exposure produces heavy Lake Michigan wind under most weather patterns. Cool late-season conditions with occasional snow.",
        "road": "Eastern Conference road environments span coastal Northeast venues and Southeast humidity.",
        "angle": "Lake Michigan wind is the defining Soldier Field weather feature. Late-season MLS matches with sustained lake wind are the highest-leverage weather reads."},
    "FC Cincinnati": {"slug": "fc-cincinnati", "stadium": "TQL Stadium",
        "headline": "FC Cincinnati Weather Playbook: TQL Stadium Ohio River Setting",
        "home": "FC Cincinnati plays at TQL Stadium in the West End of Cincinnati. Open-air Ohio River valley setting with warm humid summer conditions and cold-front-driven late-season variability.",
        "road": "Eastern Conference road environments span coastal Northeast, Southeast humidity, and Chicago lake wind.",
        "angle": "River-valley setting and cold-front-driven weather shifts are the primary weather variables. Summer heat with afternoon thunderstorm risk is elevated."},
    "Columbus Crew": {"slug": "columbus-crew", "stadium": "Lower.com Field",
        "headline": "Columbus Crew Weather Playbook: Lower.com Field Ohio Conditions",
        "home": "Columbus Crew plays at Lower.com Field near downtown Columbus. Open-air Midwest setting with warm humid summer conditions and cold late-season variability.",
        "road": "Eastern Conference road environments include coastal Northeast, Southeast humidity, and Chicago lake wind.",
        "angle": "Ohio River valley climate similar to Cincinnati. Late-season cold and cold-front-driven weather shifts are the main variables."},
    "D.C. United": {"slug": "dc-united", "stadium": "Audi Field",
        "headline": "D.C. United Weather Playbook: Audi Field Mid-Atlantic Conditions",
        "home": "D.C. United plays at Audi Field in Southwest DC. Open-air mid-Atlantic climate with hot humid summer conditions and cool late-season variability with Nor'easter risk.",
        "road": "Eastern Conference road environments span coastal Northeast humidity, Southeast, Toronto retractable.",
        "angle": "Late-season Nor'easter-driven wind and rain are the primary weather angle. Summer heat and afternoon thunderstorm risk are the main variables through August."},
    "Inter Miami CF": {"slug": "inter-miami", "stadium": "Chase Stadium",
        "headline": "Inter Miami CF Weather Playbook: Chase Stadium South Florida Heat",
        "home": "Inter Miami plays at Chase Stadium in Fort Lauderdale. Open-air South Florida setting with hot humid conditions and tropical-storm risk in September and October.",
        "road": "Eastern Conference road environments range from Northeast cool (New York, Boston) to Midwest lake-influenced conditions.",
        "angle": "Tropical-system risk is a real September and October scheduling variable. Heat index and afternoon thunderstorm risk are the primary weather angles through the season."},
    "CF Montreal": {"slug": "cf-montreal", "stadium": "Stade Saputo",
        "headline": "CF Montreal Weather Playbook: Stade Saputo Quebec Conditions",
        "home": "CF Montreal plays at Stade Saputo in Montreal, Quebec. Open-air stadium in eastern Canadian climate. Early-season and late-season matches play cold; summer plays mild.",
        "road": "Eastern Conference road environments range across the US East Coast and Midwest.",
        "angle": "Cold early-season and late-season matches are the primary weather variable. Summer plays moderate."},
    "Nashville SC": {"slug": "nashville-sc", "stadium": "Geodis Park",
        "headline": "Nashville SC Weather Playbook: Geodis Park Middle Tennessee",
        "home": "Nashville SC plays at Geodis Park in Nashville. Open-air Middle Tennessee setting with warm humid summer conditions and mild late-season play.",
        "road": "Eastern Conference road environments span Northeast coastal, Southeast humidity, and Midwest variability.",
        "angle": "Warm humid summer conditions with afternoon thunderstorm risk are the primary weather variables. Late season plays mild."},
    "New England Revolution": {"slug": "new-england-revolution", "stadium": "Gillette Stadium",
        "headline": "New England Revolution Weather Playbook: Gillette Stadium Foxborough",
        "home": "New England Revolution plays at Gillette Stadium in Foxborough, shared with the NFL Patriots. Open-air coastal Northeast setting with cool early-season and late-season variability and Nor'easter risk.",
        "road": "Eastern Conference road environments span mid-Atlantic humidity, Southeast warm, Chicago lake wind, Miami heat.",
        "angle": "Coastal Nor'easter-driven wind and rain are the defining Foxborough weather variables. Early-season and late-season MLS matches often play cool."},
    "New York City FC": {"slug": "nyc-fc", "stadium": "Yankee Stadium",
        "headline": "NYCFC Weather Playbook: Yankee Stadium Bronx Setting",
        "home": "NYCFC plays home matches at Yankee Stadium in the Bronx while their permanent stadium in Queens is under construction. Open-air Bronx setting with hot humid summer conditions and Nor'easter-influenced late-season variability.",
        "road": "Eastern Conference road environments span Miami heat, DC mid-Atlantic, Toronto retractable, Chicago lake wind.",
        "angle": "Coastal storm influence and Nor'easter wind are the primary late-season weather variables. Summer heat and thunderstorm risk are the main August variables."},
    "New York Red Bulls": {"slug": "ny-red-bulls", "stadium": "Red Bull Arena",
        "headline": "New York Red Bulls Weather Playbook: Red Bull Arena Harrison NJ",
        "home": "New York Red Bulls play at Red Bull Arena in Harrison, New Jersey, just west of Manhattan. Open-air setting with typical Northeast coastal exposure.",
        "road": "Eastern Conference road environments span Miami heat, DC mid-Atlantic, Toronto retractable, Chicago lake wind.",
        "angle": "Coastal Nor'easter influence and Meadowlands-adjacent wind patterns are the primary weather variables. Late-season MLS matches often play cool."},
    "Orlando City SC": {"slug": "orlando-city", "stadium": "Inter&Co Stadium",
        "headline": "Orlando City SC Weather Playbook: Inter&Co Stadium Central Florida",
        "home": "Orlando City plays at Inter&Co Stadium in downtown Orlando. Open-air Central Florida setting with hot humid summer conditions and daily afternoon thunderstorm risk from June through September.",
        "road": "Eastern Conference road environments span Northeast cool, Midwest variability, DC mid-Atlantic.",
        "angle": "Afternoon thunderstorm delays are a real summer scheduling variable. Heat and humidity are the primary weather variables through much of the season."},
    "Philadelphia Union": {"slug": "philadelphia-union", "stadium": "Subaru Park",
        "headline": "Philadelphia Union Weather Playbook: Subaru Park Chester Delaware River",
        "home": "Philadelphia Union play at Subaru Park in Chester, Pennsylvania, on the Delaware River. Open-air mid-Atlantic setting with warm humid summer conditions and Nor'easter-influenced late-season variability.",
        "road": "Eastern Conference road environments span Northeast coastal, Southeast humidity, Toronto retractable, Chicago lake wind.",
        "angle": "Late-season Nor'easter-driven weather and river-valley wind patterns are the primary variables. Summer heat and afternoon thunderstorm risk are the main August variables."},
    "Toronto FC": {"slug": "toronto-fc", "stadium": "BMO Field",
        "headline": "Toronto FC Weather Playbook: BMO Field Lake Ontario Setting",
        "home": "Toronto FC plays at BMO Field on the shore of Lake Ontario in downtown Toronto. Open-air lakefront setting with lake-influenced wind and cool spring and fall conditions.",
        "road": "Eastern Conference road environments span coastal Northeast, Southeast humidity, Chicago lake wind, DC mid-Atlantic.",
        "angle": "Lake Ontario wind and cool marine air are the defining BMO Field weather features. Early-season and late-season matches often play cold with sustained wind."},
    "Austin FC": {"slug": "austin-fc", "stadium": "Q2 Stadium",
        "headline": "Austin FC Weather Playbook: Q2 Stadium Central Texas Heat",
        "home": "Austin FC plays at Q2 Stadium in North Austin. Open-air Central Texas Hill Country setting with extreme summer heat and Hill Country severe-weather risk.",
        "road": "Western Conference road environments span Pacific Northwest rain, mountain elevation, California marine, Kansas City plains, Chicago lake wind.",
        "angle": "Extreme summer heat is a real player-endurance factor. Late-season plays cooler. Spring severe-weather risk brings occasional delays."},
    "Colorado Rapids": {"slug": "colorado-rapids", "stadium": "Dick's Sporting Goods Park",
        "headline": "Colorado Rapids Weather Playbook: Dick's Sporting Goods Park Elevation",
        "home": "Colorado Rapids play at Dick's Sporting Goods Park in Commerce City near Denver. Open-air setting at over 5,200 feet of elevation — thin air affects ball flight and player endurance.",
        "road": "Western Conference road environments span Pacific Northwest rain, California marine, Texas heat, Kansas City plains.",
        "angle": "Mile-high elevation is the everyday factor. Ball moves faster through thin air. Late-season cold-front weather and snow risk are the main variables."},
    "FC Dallas": {"slug": "fc-dallas", "stadium": "Toyota Stadium",
        "headline": "FC Dallas Weather Playbook: Toyota Stadium North Texas",
        "home": "FC Dallas play at Toyota Stadium in Frisco, north of Dallas. Open-air North Texas setting with extreme summer heat and severe-weather risk in spring and fall.",
        "road": "Western Conference road environments span Pacific Northwest rain, California marine, Denver elevation, plains variability.",
        "angle": "Extreme summer heat is a real player-endurance factor. Severe-weather delays are a real spring and fall scheduling risk."},
    "Houston Dynamo FC": {"slug": "houston-dynamo", "stadium": "Shell Energy Stadium",
        "headline": "Houston Dynamo Weather Playbook: Shell Energy Stadium Gulf Coast",
        "home": "Houston Dynamo play at Shell Energy Stadium in East Downtown Houston. Open-air Gulf Coast setting with extreme summer heat, humidity, and tropical-storm risk.",
        "road": "Western Conference road environments span Pacific Northwest rain, California marine, Denver elevation.",
        "angle": "Extreme heat and humidity are player-endurance factors. Tropical-storm risk in September brings real scheduling variance."},
    "LA Galaxy": {"slug": "la-galaxy", "stadium": "Dignity Health Sports Park",
        "headline": "LA Galaxy Weather Playbook: Dignity Health Sports Park Carson California",
        "home": "LA Galaxy play at Dignity Health Sports Park in Carson, south of LA. Open-air Southern California marine climate with mild consistent conditions year-round.",
        "road": "Western Conference road environments span Pacific Northwest rain, mountain elevation, Texas heat, Midwest variability.",
        "angle": "Consistent mild conditions predominate. Santa Ana wind events in September and October are the main variance. Rare winter rain."},
    "Los Angeles FC": {"slug": "lafc", "stadium": "BMO Stadium",
        "headline": "LAFC Weather Playbook: BMO Stadium Los Angeles",
        "home": "LAFC play at BMO Stadium next to Exposition Park in South LA. Open-air Los Angeles setting with mild dry marine-influenced conditions.",
        "road": "Western Conference road environments span Pacific Northwest rain, mountain elevation, Texas heat.",
        "angle": "Consistent mild conditions. Santa Ana wind events are the primary variance. Rare winter rain."},
    "Minnesota United FC": {"slug": "minnesota-united", "stadium": "Allianz Field",
        "headline": "Minnesota United Weather Playbook: Allianz Field Saint Paul",
        "home": "Minnesota United play at Allianz Field in Saint Paul. Open-air Upper Midwest setting with cool early-season and late-season conditions, potential snow risk in April and October.",
        "road": "Western Conference road environments range from Pacific Northwest rain to Southwest desert to Texas heat.",
        "angle": "Early-season and late-season cold with plains wind are the primary weather variables. Summer plays mild."},
    "Portland Timbers": {"slug": "portland-timbers", "stadium": "Providence Park",
        "headline": "Portland Timbers Weather Playbook: Providence Park Pacific Northwest",
        "home": "Portland Timbers play at Providence Park in downtown Portland. Open-air Pacific Northwest marine climate with elevated rain risk through much of the MLS season.",
        "road": "Western Conference road environments span mountain elevation, California marine, Texas heat, Midwest variability.",
        "angle": "Rain is the defining Portland weather variable. Wet conditions affect footing and ball movement. Cool marine air keeps summer temperatures moderate."},
    "Real Salt Lake": {"slug": "real-salt-lake", "stadium": "America First Field",
        "headline": "Real Salt Lake Weather Playbook: America First Field Sandy Utah",
        "home": "Real Salt Lake play at America First Field in Sandy, Utah. Open-air Salt Lake Valley setting at 4,300 feet of elevation with dry mountain-adjacent climate.",
        "road": "Western Conference road environments span Pacific Northwest rain, California marine, Texas heat.",
        "angle": "Elevation affects ball flight. Dry mountain air produces consistent conditions. Late-season cold and snow risk are the main variables."},
    "San Diego FC": {"slug": "san-diego-fc", "stadium": "Snapdragon Stadium",
        "headline": "San Diego FC Weather Playbook: Snapdragon Stadium Mission Valley",
        "home": "San Diego FC play at Snapdragon Stadium in Mission Valley. Open-air San Diego marine climate with mild dry conditions predominating year-round.",
        "road": "Western Conference road environments span Pacific Northwest rain, mountain elevation, Texas heat.",
        "angle": "Consistent mild conditions. Marine layer influence keeps evenings cool. Rare winter rain is the main variance."},
    "San Jose Earthquakes": {"slug": "san-jose-earthquakes", "stadium": "PayPal Park",
        "headline": "San Jose Earthquakes Weather Playbook: PayPal Park South Bay",
        "home": "San Jose Earthquakes play at PayPal Park in South Bay. Open-air Bay Area setting with mild marine-influenced conditions and afternoon breeze off the bay.",
        "road": "Western Conference road environments span Pacific Northwest rain, mountain elevation, Texas heat.",
        "angle": "Consistent mild marine conditions predominate. Afternoon bay breeze can pick up during summer matches."},
    "Seattle Sounders FC": {"slug": "seattle-sounders", "stadium": "Lumen Field",
        "headline": "Seattle Sounders Weather Playbook: Lumen Field Pacific Northwest Rain",
        "home": "Seattle Sounders play at Lumen Field in downtown Seattle, shared with the NFL Seahawks. Open-air Pacific Northwest marine climate with elevated rain risk through much of the MLS season.",
        "road": "Western Conference road environments span mountain elevation, California marine, Texas heat.",
        "angle": "Rain is the defining Lumen Field weather variable. Wet conditions affect footing and ball movement in matches."},
    "Sporting Kansas City": {"slug": "sporting-kansas-city", "stadium": "Children's Mercy Park",
        "headline": "Sporting Kansas City Weather Playbook: Children's Mercy Park Plains",
        "home": "Sporting KC play at Children's Mercy Park in Kansas City, Kansas. Open-air Great Plains setting with sustained wind, extreme summer heat, and severe-weather risk.",
        "road": "Western Conference road environments span Pacific Northwest rain, California marine, mountain elevation, Texas heat.",
        "angle": "Sustained plains wind is a real match-play variable. Extreme summer heat and severe-weather risk are the primary weather angles."},
    "St. Louis City SC": {"slug": "st-louis-city", "stadium": "Energizer Park",
        "headline": "St. Louis City SC Weather Playbook: Energizer Park Downtown St. Louis",
        "home": "St. Louis City SC play at Energizer Park in downtown St. Louis. Open-air Midwest setting with hot humid summer conditions and cold-front-driven variability.",
        "road": "Western Conference road environments span Pacific Northwest rain, California marine, Texas heat.",
        "angle": "Hot humid summer conditions with afternoon thunderstorm risk are the primary weather variables. Late-season cold-front games bring wind and cool temperatures."},
    "Vancouver Whitecaps FC": {"slug": "vancouver-whitecaps", "stadium": "BC Place",
        "headline": "Vancouver Whitecaps Weather Playbook: BC Place Fixed Roof",
        "home": "Vancouver Whitecaps play at BC Place in downtown Vancouver. Fixed roof stadium — every home match plays in climate-controlled indoor conditions regardless of Pacific Northwest weather outside.",
        "road": "Western Conference road environments span mountain elevation, California marine, Texas heat, Midwest variability.",
        "angle": "Zero weather variance for Vancouver home matches. Away matches in outdoor venues are where weather handicapping matters."},
}

STADIUM_CONTENT_MLS = {}
_seen = set()
for team_name, tc in TEAM_CONTENT_MLS.items():
    stadium_name = tc["stadium"]
    if stadium_name in _seen:
        continue
    _seen.add(stadium_name)
    STADIUM_CONTENT_MLS[stadium_name] = {
        "slug": tc["slug"] + "-stadium",
        "team": team_name,
        "headline": f"{stadium_name} MLS Weather Guide",
        "climate": tc["home"],
        "angle": tc["angle"],
    }

# Slug lookups
TEAM_BY_SLUG_MLS = {c["slug"]: (name, c) for name, c in TEAM_CONTENT_MLS.items()}
STADIUM_BY_SLUG_MLS = {c["slug"]: (name, c) for name, c in STADIUM_CONTENT_MLS.items()}
