"""Per-club + per-stadium content for Premier League landing pages.

2026-27 Premier League season, 20 clubs. Content anchored in verifiable
facts: club location, stadium name, capacity, general climate reputation.
No specific climatology numbers.
"""

# 20 clubs for 2026-27 season with basic venue data
TEAM_CONTENT_PREM = {
    "Arsenal": {"slug": "arsenal", "stadium": "Emirates Stadium", "city": "London", "capacity": 60704,
        "headline": "Arsenal Weather Playbook: Emirates Stadium and London Conditions",
        "home": "Arsenal play at Emirates Stadium in North London. Open-air setting with typical southeast England conditions: mild summers with rain risk, cool wet late-season conditions from November through March.",
        "road": "Premier League road environments span the length of England: coastal Brighton, Merseyside rain at Anfield and Everton, Manchester wet, Newcastle North Sea cold, Midlands variability.",
        "angle": "London weather is milder than most of England. Rain risk is elevated November through March. Wet conditions affect ball movement and passing accuracy."},
    "Aston Villa": {"slug": "aston-villa", "stadium": "Villa Park", "city": "Birmingham", "capacity": 42657,
        "headline": "Aston Villa Weather Playbook: Villa Park and West Midlands Climate",
        "home": "Aston Villa play at Villa Park in Aston, Birmingham. Open-air West Midlands setting with cool damp conditions predominating from October onward.",
        "road": "Premier League road trips span the country. Manchester and Merseyside road matches face the wettest conditions on the schedule.",
        "angle": "Midlands weather runs moderate with elevated rain risk. Late-season cold and wet conditions are the primary weather variables."},
    "Bournemouth": {"slug": "bournemouth", "stadium": "Vitality Stadium", "city": "Bournemouth", "capacity": 11307,
        "headline": "Bournemouth Weather Playbook: Vitality Stadium South Coast Setting",
        "home": "Bournemouth play at Vitality Stadium (Dean Court) on the English south coast. Open-air setting with milder conditions than most Premier League venues due to Channel-influenced climate.",
        "road": "Road environments include colder Northern venues, Merseyside rain, and Midlands variability.",
        "angle": "South Coast conditions are milder than typical Premier League venues. Late-season storm risk from Channel weather systems is the main variable."},
    "Brentford": {"slug": "brentford", "stadium": "Gtech Community Stadium", "city": "London", "capacity": 17250,
        "headline": "Brentford Weather Playbook: Gtech Community Stadium West London",
        "home": "Brentford play at Gtech Community Stadium in West London. Open-air setting with typical London mild climate and elevated rain risk in autumn and winter.",
        "road": "Premier League road trips span the country's climate variability from mild south coast to cold north.",
        "angle": "London weather is milder than most Premier League venues. Rain risk affects match conditions November through March."},
    "Brighton": {"slug": "brighton", "stadium": "Amex Stadium", "city": "Brighton", "capacity": 31800,
        "headline": "Brighton Weather Playbook: Amex Stadium South Coast Marine",
        "home": "Brighton play at Amex Stadium (Falmer) on the South Coast. Open-air setting with Channel-influenced marine climate, milder than inland English venues.",
        "road": "Road environments include colder Northern venues at Newcastle, Sunderland, and Merseyside plus inland Midlands variability.",
        "angle": "South Coast marine climate keeps conditions milder than most Premier League venues. Coastal wind and storm-driven rain are the primary variables."},
    "Chelsea": {"slug": "chelsea", "stadium": "Stamford Bridge", "city": "London", "capacity": 40341,
        "headline": "Chelsea Weather Playbook: Stamford Bridge West London Climate",
        "home": "Chelsea play at Stamford Bridge in Fulham. Open-air West London setting with mild climate and typical London rain risk in autumn and winter.",
        "road": "Premier League road trips include Manchester and Merseyside wet, Newcastle cold, and Midlands variability.",
        "angle": "London conditions are among the mildest in the Premier League. Winter rain and cold-front-driven weather are the main variables."},
    "Coventry City": {"slug": "coventry-city", "stadium": "Coventry Building Society Arena", "city": "Coventry", "capacity": 32609,
        "headline": "Coventry City Weather Playbook: Coventry Building Society Arena Midlands",
        "home": "Coventry City play at Coventry Building Society Arena in Coventry. Open-air West Midlands setting with cool damp conditions predominating from autumn onward.",
        "road": "Newly promoted for 2026-27. Road environments span the full Premier League climate range.",
        "angle": "West Midlands weather runs moderate with elevated rain risk. Late-season cold-front-driven conditions are the main weather variables."},
    "Crystal Palace": {"slug": "crystal-palace", "stadium": "Selhurst Park", "city": "London", "capacity": 25486,
        "headline": "Crystal Palace Weather Playbook: Selhurst Park South London",
        "home": "Crystal Palace play at Selhurst Park in South London. Open-air setting with mild London climate and rain risk elevated November through March.",
        "road": "Premier League road environments span coastal to Northern venues with significant weather variance.",
        "angle": "London mild climate predominates. Rain and wet-conditions matches are the primary weather angle for South London home fixtures."},
    "Everton": {"slug": "everton", "stadium": "Hill Dickinson Stadium", "city": "Liverpool", "capacity": 52888,
        "headline": "Everton Weather Playbook: Hill Dickinson Stadium Merseyside Waterfront",
        "home": "Everton play at Hill Dickinson Stadium, the new waterfront stadium on Liverpool's Bramley-Moore Dock. Open-air setting directly on the Mersey with elevated wind and rain exposure.",
        "road": "Premier League road environments include London mild, Midlands variability, Newcastle North Sea cold, and Manchester rain.",
        "angle": "Merseyside waterfront setting produces the highest wind and rain exposure in the Premier League. Wet conditions predominate through much of the season."},
    "Fulham": {"slug": "fulham", "stadium": "Craven Cottage", "city": "London", "capacity": 25700,
        "headline": "Fulham Weather Playbook: Craven Cottage Thames Riverside",
        "home": "Fulham play at Craven Cottage on the north bank of the Thames in West London. Open-air riverside setting with typical London mild climate and rain risk.",
        "road": "Premier League road environments span the full climate range from South Coast mild to Northern cold.",
        "angle": "Thames-side London climate is mild with elevated rain risk November through March. River-driven weather patterns can affect afternoon conditions."},
    "Hull City": {"slug": "hull-city", "stadium": "MKM Stadium", "city": "Kingston upon Hull", "capacity": 25404,
        "headline": "Hull City Weather Playbook: MKM Stadium East Yorkshire Coast",
        "home": "Hull City play at MKM Stadium in Kingston upon Hull. Open-air East Yorkshire coastal setting with elevated North Sea wind and cold, cool damp conditions predominating.",
        "road": "Newly promoted for 2026-27. Road environments span the full Premier League climate range.",
        "angle": "East Yorkshire coast produces cold and windy conditions from autumn through spring. North Sea storm systems are the primary weather variables."},
    "Ipswich Town": {"slug": "ipswich-town", "stadium": "Portman Road", "city": "Ipswich", "capacity": 30056,
        "headline": "Ipswich Town Weather Playbook: Portman Road East Anglia",
        "home": "Ipswich Town play at Portman Road in Ipswich. Open-air East Anglia setting with cool conditions and rain risk from October onward. North Sea influence keeps late season cold.",
        "road": "Premier League road environments span the full climate range from South Coast to Merseyside rain.",
        "angle": "East Anglia weather runs cool damp through much of the season. Late-season cold and wet conditions are the primary weather variables."},
    "Leeds United": {"slug": "leeds-united", "stadium": "Elland Road", "city": "Leeds", "capacity": 37792,
        "headline": "Leeds United Weather Playbook: Elland Road West Yorkshire",
        "home": "Leeds United play at Elland Road in Leeds. Open-air West Yorkshire setting with cool damp conditions and elevated wet-weather risk. Pennine-influenced climate.",
        "road": "Premier League road environments span the full climate range from South Coast mild to Manchester rain.",
        "angle": "West Yorkshire wet conditions predominate through much of the season. Pennine wind and rain are the primary weather variables."},
    "Liverpool": {"slug": "liverpool", "stadium": "Anfield", "city": "Liverpool", "capacity": 61276,
        "headline": "Liverpool Weather Playbook: Anfield Merseyside Rain",
        "home": "Liverpool play at Anfield. Open-air Merseyside setting with elevated rain risk through much of the season. Northwest England climate produces wet conditions and cool temperatures.",
        "road": "Premier League road environments span London mild, Midlands variability, Newcastle cold, and Yorkshire wet.",
        "angle": "Anfield rain is the defining variable. Wet-conditions matches predominate from autumn through spring. Ball movement and passing accuracy affected."},
    "Manchester City": {"slug": "manchester-city", "stadium": "Etihad Stadium", "city": "Manchester", "capacity": 53500,
        "headline": "Manchester City Weather Playbook: Etihad Stadium Manchester Climate",
        "home": "Manchester City play at Etihad Stadium in East Manchester. Open-air Northwest England setting with elevated rain risk and cool damp conditions predominating.",
        "road": "Premier League road environments span London mild, Midlands variability, Newcastle cold, and Merseyside rain.",
        "angle": "Manchester rain is the defining weather variable. Wet conditions affect match play from autumn through spring."},
    "Manchester United": {"slug": "manchester-united", "stadium": "Old Trafford", "city": "Manchester", "capacity": 74310,
        "headline": "Manchester United Weather Playbook: Old Trafford Manchester Climate",
        "home": "Manchester United play at Old Trafford. Open-air Northwest England setting with elevated rain risk predominating through much of the season. Largest club stadium in the UK.",
        "road": "Premier League road environments span the full climate range from South Coast mild to East Coast cold.",
        "angle": "Manchester rain and cool damp conditions are the defining variables. Wet-condition matches affect ball movement and passing dynamics."},
    "Newcastle United": {"slug": "newcastle-united", "stadium": "St James' Park", "city": "Newcastle upon Tyne", "capacity": 52305,
        "headline": "Newcastle United Weather Playbook: St James' Park North East Coast",
        "home": "Newcastle United play at St James' Park in Newcastle upon Tyne. Open-air North East coastal setting with elevated North Sea cold and wind, cool damp conditions predominating.",
        "road": "Premier League road environments include London mild, Manchester rain, Midlands variability, South Coast mild.",
        "angle": "North Sea wind and cold are the primary weather variables. Late-season and winter matches often play in freezing conditions with sustained wind."},
    "Nottingham Forest": {"slug": "nottingham-forest", "stadium": "City Ground", "city": "Nottingham", "capacity": 30445,
        "headline": "Nottingham Forest Weather Playbook: City Ground Trent-side",
        "home": "Nottingham Forest play at City Ground on the south bank of the River Trent. Open-air East Midlands setting with cool damp conditions from autumn through spring.",
        "road": "Premier League road environments span the full climate range.",
        "angle": "East Midlands weather runs moderate with elevated rain risk. River Trent influence keeps humidity elevated. Late-season cold and wet are the primary variables."},
    "Sunderland": {"slug": "sunderland", "stadium": "Stadium of Light", "city": "Sunderland", "capacity": 49000,
        "headline": "Sunderland Weather Playbook: Stadium of Light North East Coast",
        "home": "Sunderland play at Stadium of Light in Sunderland. Open-air North East coastal setting with North Sea cold and wind, cool damp conditions from autumn onward.",
        "road": "Premier League road environments span the full climate range.",
        "angle": "North Sea wind and cold are the defining weather variables. Late-season and winter matches face freezing conditions with sustained coastal wind."},
    "Tottenham Hotspur": {"slug": "tottenham-hotspur", "stadium": "Tottenham Hotspur Stadium", "city": "London", "capacity": 62850,
        "headline": "Tottenham Hotspur Weather Playbook: Tottenham Hotspur Stadium North London",
        "home": "Tottenham play at Tottenham Hotspur Stadium in North London. Open-air setting with typical London mild climate and elevated rain risk November through March.",
        "road": "Premier League road environments span the full climate range from South Coast mild to Northern cold.",
        "angle": "London conditions are among the mildest in the Premier League. Winter rain and cold-front-driven weather are the main variables."},
}

# Stadium content derived from team dict (1:1 mapping)
STADIUM_CONTENT_PREM = {}
for team_name, tc in TEAM_CONTENT_PREM.items():
    STADIUM_CONTENT_PREM[tc["stadium"]] = {
        "slug": tc["slug"] + "-stadium",
        "team": team_name,
        "city": tc["city"],
        "capacity": tc["capacity"],
        "headline": f"{tc['stadium']} Weather Guide: {tc['city']} Premier League Football",
        "overview": tc["home"],
        "angle": tc["angle"],
    }

TEAM_BY_SLUG_PREM = {c["slug"]: (name, c) for name, c in TEAM_CONTENT_PREM.items()}
STADIUM_BY_SLUG_PREM = {c["slug"]: (name, c) for name, c in STADIUM_CONTENT_PREM.items()}
