"""Per-stadium content for /ncaaf/stadium/<slug> landing pages.

Covers the top 25 most-searched FBS stadiums. Content is anchored to
facts pulled from cfb.venues.FBS_TEAMS: stadium name, city, roof, cap,
and general regional climate reputation for the CFB season (August
through January).
"""

STADIUM_CONTENT_CFB = {
    "Michigan Stadium": {"slug": "michigan-stadium", "team": "Michigan Wolverines",
        "headline": "Michigan Stadium (The Big House) Weather: Ann Arbor Great Lakes Climate",
        "intro": "Michigan Stadium in Ann Arbor is the largest stadium in North America by capacity. Open-air Great Lakes setting brings cool early-season conditions and cold late-season and playoff games with occasional snow.",
        "angle": "November home games regularly play cold with lake-influenced wind. Snow games at the Big House are on the schedule most years and materially affect kicking accuracy and passing efficiency."},
    "Beaver Stadium": {"slug": "beaver-stadium", "team": "Penn State Nittany Lions",
        "headline": "Beaver Stadium Weather: State College Pennsylvania Cold",
        "intro": "Beaver Stadium in State College is one of the largest CFB venues. Central Pennsylvania mountain setting brings variable weather with cold and windy late-season conditions.",
        "angle": "November whiteout games at Beaver Stadium regularly play in freezing conditions. Cold-front-driven wind and snow risk are the primary late-season weather variables."},
    "Ohio Stadium": {"slug": "ohio-stadium", "team": "Ohio State Buckeyes",
        "headline": "Ohio Stadium (The Horseshoe) Weather: Columbus Ohio Climate",
        "intro": "Ohio Stadium in Columbus is the horseshoe-shaped home of the Buckeyes. Open-air Midwest setting brings warm humid early-season games and cold late-season conditions.",
        "angle": "The Game with Michigan in late November regularly plays in cold and windy conditions. Cold-front wind shifts are the primary weather variable."},
    "Kyle Field": {"slug": "kyle-field", "team": "Texas A&M Aggies",
        "headline": "Kyle Field Weather: College Station Texas Heat",
        "intro": "Kyle Field in College Station brings extreme early-season heat and humidity. Central Texas climate produces warm evening games well into October.",
        "angle": "Heat index for September and early October games is a real factor for players. Cold-front-driven rain risk is elevated in late season."},
    "Tiger Stadium": {"slug": "tiger-stadium", "team": "LSU Tigers",
        "headline": "Tiger Stadium (Death Valley) Weather: Baton Rouge Gulf Coast Setting",
        "intro": "Tiger Stadium in Baton Rouge is one of the most raucous night-game environments in CFB. Gulf Coast climate brings warm humid conditions with tropical-storm risk in September and cold-front-driven rain later.",
        "angle": "Night games are the LSU home tradition; cooler evening temperatures than daytime SEC games. Tropical-storm-driven schedule changes are a real September risk."},
    "Neyland Stadium": {"slug": "neyland-stadium", "team": "Tennessee Volunteers",
        "headline": "Neyland Stadium Weather: Knoxville Tennessee River Setting",
        "intro": "Neyland Stadium sits on the Tennessee River in Knoxville. Southeast climate brings warm humid early-season games and cool late-season conditions with cold-front risk.",
        "angle": "River-valley setting and Southeast humidity affect early-season play. Late-season cold-front games bring the sharpest wind and precipitation shifts."},
    "Darrell K Royal-Texas Memorial Stadium": {"slug": "dkr-texas-memorial-stadium", "team": "Texas Longhorns",
        "headline": "DKR Texas Memorial Stadium Weather: Austin Texas Heat",
        "intro": "DKR-Texas Memorial in Austin brings extreme early-season heat. Central Texas climate produces warm conditions well into November.",
        "angle": "Heat index for September and October games is significant. Late-season cold-front games bring occasional cool wet conditions."},
    "Bryant-Denny Stadium": {"slug": "bryant-denny-stadium", "team": "Alabama Crimson Tide",
        "headline": "Bryant-Denny Stadium Weather: Tuscaloosa Alabama SEC Setting",
        "intro": "Bryant-Denny in Tuscaloosa hosts Alabama football. Southeast climate brings warm humid early-season games and mild late-season conditions.",
        "angle": "Southeast humidity and afternoon thunderstorm risk are the primary early-season weather variables. Cold-front-driven wind shifts are the main late-season factor."},
    "Sanford Stadium": {"slug": "sanford-stadium", "team": "Georgia Bulldogs",
        "headline": "Sanford Stadium (Between the Hedges) Weather: Athens Georgia",
        "intro": "Sanford Stadium in Athens is home of the Georgia Bulldogs and their iconic hedges. Southeast climate brings warm humid early-season games and mild late-season play.",
        "angle": "Southeast humidity affects early-season conditions. Late-season cold-front games and rare late-November cool snaps are the primary weather variables."},
    "Rose Bowl": {"slug": "rose-bowl", "team": "UCLA Bruins",
        "headline": "Rose Bowl Weather: Pasadena California Setting",
        "intro": "The Rose Bowl in Pasadena hosts UCLA home games and the Rose Bowl Game on New Year's Day. Southern California climate brings mild dry conditions year-round.",
        "angle": "Consistent mild conditions predominate. Rare December and January rain is the main variance from the mild baseline. Santa Ana wind events in fall can bring elevated wind speeds."},
    "Ben Hill Griffin Stadium": {"slug": "ben-hill-griffin-stadium", "team": "Florida Gators",
        "headline": "Ben Hill Griffin Stadium (The Swamp) Weather: Gainesville Florida",
        "intro": "The Swamp in Gainesville brings extreme early-season Florida heat and afternoon thunderstorm risk. Central Florida climate produces warm humid conditions through much of the season.",
        "angle": "Afternoon thunderstorm delays are a real September risk. Heat index is a factor for early-season games. Late-season plays mild."},
    "Jordan-Hare Stadium": {"slug": "jordan-hare-stadium", "team": "Auburn Tigers",
        "headline": "Jordan-Hare Stadium Weather: Auburn Alabama SEC Setting",
        "intro": "Jordan-Hare in Auburn brings warm humid early-season SEC play. Southeast climate with cold-front-driven late-season variability.",
        "angle": "Southeast humidity and afternoon thunderstorm risk are the primary early-season variables. Late-season cold-front games are the main weather leverage."},
    "Memorial Stadium (Lincoln)": {"slug": "memorial-stadium-nebraska", "team": "Nebraska Cornhuskers",
        "headline": "Memorial Stadium Weather: Lincoln Nebraska Plains Setting",
        "intro": "Memorial Stadium in Lincoln brings Great Plains weather. Late-season games can play in freezing cold with sustained plains wind.",
        "angle": "Plains wind and late-season cold are the primary weather variables. November games regularly play with sustained wind that affects kicking and passing."},
    "Memorial Stadium (Clemson)": {"slug": "memorial-stadium-clemson", "team": "Clemson Tigers",
        "headline": "Memorial Stadium (Death Valley) Weather: Clemson South Carolina Foothills",
        "intro": "Memorial Stadium in Clemson sits at the foot of the Blue Ridge foothills. Southeast climate with warm humid early-season games and mild late-season play.",
        "angle": "Southeast humidity and afternoon thunderstorm risk are early-season variables. Foothills setting produces occasional weather channeling effects."},
    "Camp Randall Stadium": {"slug": "camp-randall-stadium", "team": "Wisconsin Badgers",
        "headline": "Camp Randall Stadium Weather: Madison Wisconsin Cold",
        "intro": "Camp Randall in Madison brings Upper Midwest weather. Late-season games play in freezing conditions with lake-influenced wind and occasional snow.",
        "angle": "November home games regularly play cold with plains wind. Snow games are on the schedule most years."},
    "Gaylord Family Oklahoma Memorial Stadium": {"slug": "oklahoma-memorial-stadium", "team": "Oklahoma Sooners",
        "headline": "Oklahoma Memorial Stadium Weather: Norman Oklahoma Plains",
        "intro": "Oklahoma Memorial Stadium in Norman brings Great Plains weather. Early-season heat gives way to variable late-season conditions with severe-weather risk.",
        "angle": "Plains wind and severe-weather risk are the primary weather variables. Late-season cold-front games bring the sharpest wind shifts."},
    "Doak Campbell Stadium": {"slug": "doak-campbell-stadium", "team": "Florida State Seminoles",
        "headline": "Doak Campbell Stadium Weather: Tallahassee Florida Panhandle",
        "intro": "Doak Campbell in Tallahassee brings Florida Panhandle weather. Warm humid early-season play with tropical-storm risk in September.",
        "angle": "Tropical-storm-driven schedule changes are a real September risk. Afternoon thunderstorm delays and heat are the primary early-season variables."},
    "Notre Dame Stadium": {"slug": "notre-dame-stadium", "team": "Notre Dame Fighting Irish",
        "headline": "Notre Dame Stadium Weather: South Bend Great Lakes Cold",
        "intro": "Notre Dame Stadium in South Bend brings Great Lakes weather. Late-season games play cold with lake-influenced wind and occasional snow.",
        "angle": "November home games regularly play cold with sustained wind. Snow games are common. Cold-weather Notre Dame games are a classic CFB environment."},
    "Williams-Brice Stadium": {"slug": "williams-brice-stadium", "team": "South Carolina Gamecocks",
        "headline": "Williams-Brice Stadium Weather: Columbia South Carolina SEC",
        "intro": "Williams-Brice in Columbia brings Southeast warm humid conditions. Early-season heat and afternoon thunderstorm risk are elevated.",
        "angle": "Southeast humidity and afternoon storm delays are the primary weather variables. Late-season plays mild with occasional cold-front influence."},
    "Los Angeles Memorial Coliseum": {"slug": "la-memorial-coliseum", "team": "USC Trojans",
        "headline": "LA Memorial Coliseum Weather: USC Southern California Setting",
        "intro": "The LA Memorial Coliseum hosts USC football. Southern California climate brings mild dry conditions year-round with Santa Ana wind events in fall.",
        "angle": "Consistent mild conditions predominate. Santa Ana wind events in September and October are the primary variance."},
    "Donald W. Reynolds Razorback Stadium": {"slug": "razorback-stadium", "team": "Arkansas Razorbacks",
        "headline": "Reynolds Razorback Stadium Weather: Fayetteville Ozark Mountain Setting",
        "intro": "Razorback Stadium in Fayetteville sits in the Ozark foothills. Mid-South climate with warm humid early season and cool late-season conditions.",
        "angle": "Ozark elevation and cold-front-driven weather shifts are the primary variables. Late-season cold-front games bring wind and rain."},
    "Spartan Stadium": {"slug": "spartan-stadium", "team": "Michigan State Spartans",
        "headline": "Spartan Stadium Weather: East Lansing Michigan",
        "intro": "Spartan Stadium in East Lansing brings Great Lakes weather. Late-season games play cold with lake-influenced wind and occasional snow.",
        "angle": "November home games regularly play cold. Snow risk is elevated in late season. Cold-weather rivalry games against Michigan are the primary weather leverage."},
    "Husky Stadium": {"slug": "husky-stadium", "team": "Washington Huskies",
        "headline": "Husky Stadium Weather: Seattle Pacific Northwest Rain",
        "intro": "Husky Stadium in Seattle sits on Lake Washington. Pacific Northwest marine climate brings mild wet conditions through much of the season.",
        "angle": "Rain is the defining Seattle weather variable. Late-season and playoff games often play in steady rain that affects ball security and kicking."},
    "Kinnick Stadium": {"slug": "kinnick-stadium", "team": "Iowa Hawkeyes",
        "headline": "Kinnick Stadium Weather: Iowa City Plains Cold",
        "intro": "Kinnick Stadium in Iowa City brings Upper Midwest weather. Late-season games play cold with sustained plains wind and occasional snow.",
        "angle": "Plains wind and late-season cold are the primary weather variables. Kinnick's open setting means wind reaches the field with little obstruction."},
    "Lane Stadium": {"slug": "lane-stadium", "team": "Virginia Tech Hokies",
        "headline": "Lane Stadium Weather: Blacksburg Appalachian Setting",
        "intro": "Lane Stadium in Blacksburg sits in the Appalachian Mountains. Elevated setting produces cooler conditions than the Virginia lowlands and elevated storm risk.",
        "angle": "Mountain-driven weather including afternoon thunderstorm risk and cool November games are the primary weather variables."},
}

STADIUM_BY_SLUG_CFB = {c["slug"]: (name, c) for name, c in STADIUM_CONTENT_CFB.items()}
