"""Per-track content blocks for /nascar/track/<slug> landing pages.

Content anchored to verifiable track metadata: track type, length,
city, and general climate. NASCAR races primarily in daylight and
early evening from mid-February through November. Rain typically
delays or postpones races (road courses can run in light rain).
"""

def _slugify(name):
    import re
    s = name.lower()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s).strip("-")
    return s


TRACK_CONTENT = {
    "Daytona International Speedway": {"slug": "daytona-international-speedway",
        "headline": "Daytona International Speedway Weather: Superspeedway Draft and Florida Storm Risk",
        "context": "Daytona is a 2.5-mile superspeedway with high-banking turns in Daytona Beach, Florida. The February Daytona 500 opens the Cup season and the summer Coke Zero Sugar 400 runs in August. Late-summer Florida afternoons carry significant thunderstorm risk.",
        "weather_angle": "Rain delays are the primary NASCAR weather concern at Daytona. Coastal setting brings sea-breeze thunderstorm development on summer afternoons and evenings. Wind affects superspeedway drafting patterns; strong crosswinds through the trioval can shift pack behavior.",
        "betting_angle": "Track temperature affects tire grip on the high-banked corners. Rain delays that force a night finish change the racing profile as the surface cools. Radar risk during the August race is the main handicap."},
    "Talladega Superspeedway": {"slug": "talladega-superspeedway",
        "headline": "Talladega Superspeedway Weather: 2.66-Mile Superspeedway in Alabama",
        "context": "Talladega is the largest oval on the NASCAR schedule at 2.66 miles with 33-degree banking. Located in Lincoln, Alabama. Spring race in April, fall race in October.",
        "weather_angle": "Wind is the story at Talladega. Crosswinds through the massive trioval affect drafting stability and can push cars sideways at 200 mph. Alabama afternoon thunderstorm risk in April and October brings rain delays.",
        "betting_angle": "Wind speed and direction are the primary weather handicaps. Cool air with headwinds increases downforce and drafting effectiveness. Warm air with tailwinds destabilizes the pack."},
    "Atlanta Motor Speedway": {"slug": "atlanta-motor-speedway",
        "headline": "Atlanta Motor Speedway Weather: Reconfigured Superspeedway in Georgia",
        "context": "Atlanta is a 1.54-mile oval in Hampton, Georgia. The 2022 reconfiguration steepened banking to 28 degrees and now races closer to superspeedway pack style than traditional intermediate. Two Cup races per season.",
        "weather_angle": "Georgia summer thunderstorm risk brings rain delays for the summer race. Wind affects drafting under the new configuration similar to superspeedway effects.",
        "betting_angle": "Radar risk and heat-driven tire wear are the primary weather angles. Post-reconfiguration race style is more weather-sensitive than the old intermediate profile."},
    "Las Vegas Motor Speedway": {"slug": "las-vegas-motor-speedway",
        "headline": "Las Vegas Motor Speedway Weather: 1.5-Mile Intermediate in the Desert",
        "context": "Las Vegas is a 1.5-mile intermediate oval in the desert north of the strip. Two Cup races: spring in March and playoff race in October.",
        "weather_angle": "Desert climate produces heat and low humidity. Track temperature swings dramatically between day and night, affecting tire grip and setup. Rain is rare but does occur in spring and fall.",
        "betting_angle": "Track surface temperature is the primary weather variable. Hot afternoon races produce different racing than cooler evening laps. Long green-flag runs favor teams with the best tire management in the heat."},
    "Texas Motor Speedway": {"slug": "texas-motor-speedway",
        "headline": "Texas Motor Speedway Weather: North Texas Intermediate Oval",
        "context": "Texas is a 1.5-mile intermediate oval in Fort Worth. The reconfigured surface produces high-line racing. Spring and playoff races.",
        "weather_angle": "North Texas heat and thunderstorm risk are the primary weather concerns. Spring races can see severe-weather-driven delays. Summer heat pushes track temperatures high, affecting tire wear.",
        "betting_angle": "Heat and radar risk are the primary handicaps. Wet conditions force rain delays on the paved oval; no wet racing at Texas."},
    "Charlotte Motor Speedway": {"slug": "charlotte-motor-speedway",
        "headline": "Charlotte Motor Speedway Weather: Home of NASCAR, Roval Configuration",
        "context": "Charlotte is a 1.5-mile intermediate oval in Concord, North Carolina, near NASCAR's home base. Coca-Cola 600 in May is the longest race in NASCAR. Roval configuration for fall race uses the infield road course.",
        "weather_angle": "Southeast summer heat and thunderstorm risk are the primary weather concerns for the 600. Fall Roval race in October can see cool temperatures and rain, and the road-course layout allows wet racing.",
        "betting_angle": "Coca-Cola 600 heat and endurance are the classic weather angle. Roval fall race handicapping includes wet-conditions competitiveness under the road-course rules."},
    "Kansas Speedway": {"slug": "kansas-speedway",
        "headline": "Kansas Speedway Weather: Plains Intermediate Oval",
        "context": "Kansas is a 1.5-mile intermediate oval in Kansas City, Kansas. Spring race in May and playoff race in September or October.",
        "weather_angle": "Plains climate produces sustained wind that can affect racing lines and tire wear. Late-May severe-weather risk includes tornado watches. Fall race plays cooler and clearer typically.",
        "betting_angle": "Plains wind and severe-weather delay risk are the primary weather angles. Long green-flag runs favor teams with strong tire management."},
    "Michigan International Speedway": {"slug": "michigan-international-speedway",
        "headline": "Michigan International Speedway Weather: 2-Mile D-Shaped Oval",
        "context": "Michigan is a 2-mile D-shaped oval in Brooklyn, Michigan. High-speed track with 18-degree banking. Summer race in August.",
        "weather_angle": "Michigan summer weather runs warm and humid. Lake-driven thunderstorm risk brings rain delays. Track surface temperature affects tire grip on the fast oval.",
        "betting_angle": "Heat and radar risk are the primary weather handicaps. Track temperature swings affect setup preferences through the race."},
    "Homestead-Miami Speedway": {"slug": "homestead-miami-speedway",
        "headline": "Homestead-Miami Speedway Weather: South Florida Intermediate",
        "context": "Homestead is a 1.5-mile oval with variable banking in Homestead, Florida. Playoff race late in the season, historically the championship-race venue.",
        "weather_angle": "South Florida climate keeps November races mild. Tropical-storm season is winding down but rain risk remains elevated. Track surface holds heat well.",
        "betting_angle": "Warm weather produces higher tire wear than typical late-season races. Championship-decisive races here have historically played with clear skies but Florida rain risk is nonzero."},
    "Pocono Raceway": {"slug": "pocono-raceway",
        "headline": "Pocono Raceway Weather: Tricky Triangle in the Poconos",
        "context": "Pocono is a 2.5-mile triangular oval in Long Pond, Pennsylvania. Three distinct corners with different characteristics. Cup race in June.",
        "weather_angle": "Mountain setting produces cool temperatures and rain risk. Cold-front-driven weather can bring afternoon showers on race day.",
        "betting_angle": "Cool weather affects tire warm-up on the tricky triangle. Rain delays are common because of Pocono's mountain-driven thunderstorm pattern."},
    "Bristol Motor Speedway": {"slug": "bristol-motor-speedway",
        "headline": "Bristol Motor Speedway Weather: High-Banked Short Track in Tennessee",
        "context": "Bristol is a 0.533-mile short track with steep banking in Bristol, Tennessee. Night race under lights in September and spring dirt race format for early-season race.",
        "weather_angle": "Tennessee mountain climate produces variable spring conditions. Night race running under lights sees cooling temperatures through the event.",
        "betting_angle": "Track surface temperature drop through the night race affects tire grip. Rain delays force schedule adjustments; the concrete surface does not allow wet racing."},
    "Martinsville Speedway": {"slug": "martinsville-speedway",
        "headline": "Martinsville Speedway Weather: Paperclip Short Track in Virginia",
        "context": "Martinsville is a 0.526-mile paperclip-shaped oval in Ridgeway, Virginia. NASCAR's shortest oval. Spring and fall Cup races.",
        "weather_angle": "Fall race in October or November regularly plays in cold conditions with occasional snow risk in the Virginia foothills. Rain delays force schedule shifts.",
        "betting_angle": "Cold weather affects tire warm-up and grip at the short track. Late-season Martinsville races with sub-50-degree temperatures are the classic short-track weather environment."},
    "Richmond Raceway": {"slug": "richmond-raceway",
        "headline": "Richmond Raceway Weather: D-Shaped Short Track in Virginia",
        "context": "Richmond is a 0.75-mile D-shaped short track in Richmond, Virginia. Two Cup races: spring and playoff.",
        "weather_angle": "Mid-Atlantic climate produces moderate conditions. Spring races can see cool weather; playoff race in early season plays warm and humid.",
        "betting_angle": "Track temperature affects tire management on the short flat oval. Rain delays force schedule shifts but Richmond races typically finish on schedule."},
    "Phoenix Raceway": {"slug": "phoenix-raceway",
        "headline": "Phoenix Raceway Weather: Desert Short Oval and Championship Finale",
        "context": "Phoenix is a 1-mile oval in Avondale, Arizona. Championship-race venue since 2020. Spring race also on the schedule.",
        "weather_angle": "Desert climate produces dry heat and low humidity. Championship race in November runs mild. Rain is rare but does occur.",
        "betting_angle": "Dry desert air and cool November temperatures produce consistent racing conditions at the championship venue. Track temperature is the primary variable."},
    "Dover Motor Speedway": {"slug": "dover-motor-speedway",
        "headline": "Dover Motor Speedway Weather: Monster Mile Concrete Oval",
        "context": "Dover is a 1-mile concrete oval in Dover, Delaware. Steep 24-degree banking and concrete surface. Cup race in the spring.",
        "weather_angle": "Mid-Atlantic climate with coastal storm-track exposure. Rain delays are common and the concrete surface does not allow wet racing.",
        "betting_angle": "Track temperature and concrete surface behavior are the primary weather variables. Rain risk is the main delay handicap."},
    "New Hampshire Motor Speedway": {"slug": "new-hampshire-motor-speedway",
        "headline": "New Hampshire Motor Speedway Weather: Flat 1-Mile Oval in Loudon",
        "context": "New Hampshire is a 1.06-mile flat oval in Loudon, New Hampshire. Cup race in mid-summer.",
        "weather_angle": "New England summer weather runs warm with afternoon thunderstorm risk. Coastal cool fronts can drop temperatures through the race.",
        "betting_angle": "Track surface temperature and cold-front-driven weather shifts are the primary variables. Rain delays are common in humid summer conditions."},
    "Iowa Speedway": {"slug": "iowa-speedway",
        "headline": "Iowa Speedway Weather: Newton Iowa Short Track",
        "context": "Iowa Speedway is a 0.875-mile short oval in Newton, Iowa. Cup race added to the schedule in recent seasons.",
        "weather_angle": "Iowa summer weather runs warm and humid with elevated severe-weather risk. Afternoon thunderstorms and tornado watches can affect race scheduling.",
        "betting_angle": "Severe-weather delay risk and track surface temperature are the primary weather angles. Long green-flag runs test tire management in Iowa heat."},
    "Nashville Superspeedway": {"slug": "nashville-superspeedway",
        "headline": "Nashville Superspeedway Weather: 1.33-Mile Concrete Oval",
        "context": "Nashville Superspeedway is a 1.333-mile concrete oval in Lebanon, Tennessee. Cup race in late June.",
        "weather_angle": "Tennessee summer heat and afternoon thunderstorm risk are the primary weather concerns. Concrete surface affects tire wear differently than asphalt.",
        "betting_angle": "Heat and radar risk are the primary handicaps. Concrete surface temperature response is different from asphalt intermediates."},
    "Sonoma Raceway": {"slug": "sonoma-raceway",
        "headline": "Sonoma Raceway Weather: Wine Country Road Course",
        "context": "Sonoma is a 1.99-mile road course in the hills of Sonoma, California. Cup race in June.",
        "weather_angle": "Northern California summer weather runs dry and warm at Sonoma. Marine-layer morning fog is possible but typically clears before green flag. Rain is rare but wet racing is allowed on road courses.",
        "betting_angle": "Dry conditions predominate. Any moisture shifts the race dramatically; teams with strong wet-condition setups gain leverage on rare rain days."},
    "Watkins Glen International": {"slug": "watkins-glen-international",
        "headline": "Watkins Glen International Weather: Finger Lakes Road Course",
        "context": "Watkins Glen is a 2.45-mile road course in the Finger Lakes region of New York. Cup race in August.",
        "weather_angle": "Upstate New York summer weather can bring afternoon thunderstorms. Rain and wet racing are allowed on the road course.",
        "betting_angle": "Wet-condition competitiveness is the primary weather angle. Teams with strong rain setups gain leverage when Watkins Glen sees afternoon showers."},
    "Circuit of the Americas": {"slug": "circuit-of-the-americas",
        "headline": "Circuit of the Americas Weather: Austin Road Course",
        "context": "COTA is a 3.43-mile road course near Austin, Texas. Cup race in spring.",
        "weather_angle": "Texas Hill Country spring weather can be volatile with severe-weather risk. Wet racing is allowed on the road course.",
        "betting_angle": "Radar risk and wet-condition racing are the primary weather angles. Cool spring conditions produce different racing than the summer NASCAR baseline."},
    "Chicago Street Course": {"slug": "chicago-street-course",
        "headline": "Chicago Street Course Weather: Downtown Chicago Street Racing",
        "context": "Chicago Street Course is a 2.2-mile temporary street circuit through downtown Chicago. Cup race in early July.",
        "weather_angle": "Chicago summer thunderstorm risk is significant for early-July races. Lake Michigan influence brings cool onshore breezes. Wet racing is allowed on the street course.",
        "betting_angle": "Radar risk and lake-driven wind shifts are the primary weather angles. Wet racing rules make Chicago handicapping heavily rain-conditional."},
    "Coronado Street Course": {"slug": "coronado-street-course",
        "headline": "Coronado Street Course Weather: San Diego Naval Base Street Circuit",
        "context": "Coronado Street Course is a 2-mile temporary circuit at Naval Base Coronado near San Diego. Cup race added in recent seasons.",
        "weather_angle": "San Diego marine climate produces mild consistent conditions. Marine-layer morning fog is possible but typically clears. Rain is uncommon during the NASCAR race window.",
        "betting_angle": "Consistent mild conditions make Coronado one of the most weather-predictable venues on the schedule. Marine air keeps track temperature moderate."},
    "Indianapolis Motor Speedway": {"slug": "indianapolis-motor-speedway",
        "headline": "Indianapolis Motor Speedway Weather: The Brickyard",
        "context": "Indianapolis Motor Speedway is a 2.5-mile rectangular oval in Speedway, Indiana. Home of the Brickyard. Cup race format varies between oval and road-course configuration in recent seasons.",
        "weather_angle": "Midwest summer heat and thunderstorm risk are the primary weather concerns. Track surface holds heat significantly.",
        "betting_angle": "Track temperature and rain delay risk are the primary handicaps. Configuration status (oval versus infield road course) changes the wet-racing rules for the venue."},
    "Darlington Raceway": {"slug": "darlington-raceway",
        "headline": "Darlington Raceway Weather: The Lady in Black, Egg-Shaped Oval",
        "context": "Darlington is a 1.37-mile egg-shaped oval in Darlington, South Carolina. Uniquely shaped historic track. Cup races in spring and Labor Day weekend.",
        "weather_angle": "Southeast summer heat and thunderstorm risk are significant for the Labor Day race. Track surface holds heat well.",
        "betting_angle": "Heat, tire wear, and radar risk are the primary weather angles. The abrasive surface produces heavy tire wear that heat exaggerates."},
    "World Wide Technology Raceway": {"slug": "world-wide-technology-raceway",
        "headline": "World Wide Technology Raceway Weather: Gateway 1.25-Mile Oval",
        "context": "World Wide Technology Raceway is a 1.25-mile oval in Madison, Illinois, across the river from St. Louis. Cup race in early summer.",
        "weather_angle": "Midwest summer heat and severe-weather risk are the primary weather concerns. River-valley setting can produce localized thunderstorm development.",
        "betting_angle": "Heat and radar risk are the primary handicaps. The unusual 1.25-mile configuration produces racing between short-track and intermediate profiles."},
    "Auto Club Speedway": {"slug": "auto-club-speedway",
        "headline": "Auto Club Speedway Weather: Fontana 2-Mile Oval",
        "context": "Auto Club Speedway is a 2-mile D-shaped oval in Fontana, California. Historic California track undergoing reconfiguration.",
        "weather_angle": "Southern California climate produces dry conditions. Santa Ana wind events in fall can bring high wind speeds. Rain is uncommon.",
        "betting_angle": "Dry warm conditions predominate. Santa Ana wind events are the primary variance from the mild baseline."},
}

TRACK_BY_SLUG = {c["slug"]: (name, c) for name, c in TRACK_CONTENT.items()}
